# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#
# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4
floating_modifier $mod

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
font pango:Hasklig 8
# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# for_window [title="log-follow — Konsole"] move container to workspace 10
# exec --no-startup-id konsole -p LocalTabTitleFormat='log-follow' -e journalctl --user -f
# exec --no-startup-id konsole -p LocalTabTitleFormat='log-follow' -e dmesg --follow -H

for_window [class="Uzbl-core"] focus child, layout stacking, focus

# popups_during_fullscreen smart
floating_maximum_size 1280 x 768
# shmlog on

exec --no-startup-id dunst
# exec --no-startup-id pwrnotify -d 60 -d 3600 80 50 25 10 5 4 3 2 1
exec --no-startup-id unclutter -idle 5 -root
exec --no-startup-id sh -c 'sleep 2; conky'
exec --no-startup-id sh -c 'sleep 3; xcape'
exec --no-startup-id xrdb ~/.Xresources
exec --no-startup-id dropbox start
exec --no-startup-id volumeicon
# exec_always hp-systray
exec --no-startup-id nm-applet
exec --no-startup-id sh -c 'sleep 3; blueberry-tray'
exec --no-startup-id emacs --daemon
# exec_always setxkbmap -option 'caps:swapescape'
exec --no-startup-id setxkbmap -option 'ctrl:nocaps' -option 'altwin:swap_lalt_lwin' -option 'compose:ralt'
exec --no-startup-id gnome-screensaver
# exec --no-startup-id gnome-calendar
exec --no-startup-id nitrogen --restore
# exec --no-startup-id i3-msg 'workspace 10; exec /usr/bin/firefox; workspace 1'
# exec_always compton -CGb -i 0.8 -m 0.85 -f -D 15
# exec_always compton -CGb -o 0.75 -D 10 -m 1 -i 0.7 -e 0.8 --active-opacity 0.8
exec --no-startup-id compton -CGb -D 10 -m 1 --config ~/.compton
# exec i3-focus-debug
exec --no-startup-id sh -c 'sleep 5; xbacklighticon'
default_orientation auto
# hide_edge_borders smart

# for_window [title=""]/[class=""] floating enable
# for_window [title=""]/[class=""] floating disable
for_window [title="Nitrogen"] floating enable
for_window [workspace="8"] floating enable
for_window [class="Lxappearance"] floating enable
for_window [class="Inkscape" title="Properties"] floating enable

#                       border  bg      text    indic     child
# client.focused        #4c7899 #333333 #ffffff #2e9ef4   #285577
# client.focused          #000000 #000000 #ffffff #000000   #000000
# client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
# client.unfocused        #333333 #222222 #888888 #292d2e   #222222
# client.urgent           #2f343a #900000 #ffffff #900000   #900000
# client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

#                       border  bg      text    indic     child
client.focused          #1c1c1c #1c1c1c #0099ff #1c1c1c #1c1c1c
client.focused_inactive #1c1c1c #1c1c1c #aaaaaa #1c1c1c #1c1c1c
client.unfocused        #1c1c1c #1c1c1c #777777 #1c1c1c #1c1c1c
client.urgent           #1c1c1c #1c1c1c #ff0000 #1c1c1c #1c1c1c
client.placeholder      #1c1c1c #1c1c1c #333333 #1c1c1c #1c1c1c

gaps inner 4
gaps outer -4
# smart_borders no_gaps
no_focus [class="^.*"]
# new_window none
# new_float none
# for_window [class="^.*"] border none
focus_follows_mouse no

# bindsym $mod+m gtkman
bindsym $mod+m exec --no-startup-id sh -c 'python /home/lennart/tmp/top10/main.py'

bindsym $mod+z workspace back_and_forth
bindsym $mod+Shift+z move container to workspace back_and_forth
# bindsym $mod+Ctrl+j move container to workspace prev
# bindsym $mod+Ctrl+k move container to workspace next
# bindsym $mod+Ctrl+h workspace prev
# bindsym $mod+Ctrl+l workspace next

bindsym $mod+Ctrl+h resize shrink width 20 px or 20 ppt
bindsym $mod+Ctrl+j resize grow height 20 px or 20 ppt
bindsym $mod+Ctrl+k resize shrink height 20 px or 20 ppt
bindsym $mod+Ctrl+l resize grow width 20 px or 20 ppt

bindsym $mod+Ctrl+Shift+h resize shrink width 5 px or 5 ppt
bindsym $mod+Ctrl+Shift+j resize grow height 5 px or 5 ppt
bindsym $mod+Ctrl+Shift+k resize shrink height 5 px or 5 ppt
bindsym $mod+Ctrl+Shift+l resize grow width 5 px or 5 ppt

bindsym $mod+p exec --no-startup-id thunar
bindsym $mod+o exec --no-startup-id firefox
bindsym $mod+i exec --no-startup-id lxterminal -e math
bindsym $mod+u exec --no-startup-id galculator
bindsym $mod+x exec --no-startup-id gnome-screenshot -a -c
bindsym $mod+Shift+x exec --no-startup-id ~/Dropbox/dropshot.sh
# bindsym $mod+y exec xsel | xsel -i -b
bindsym $mod+t exec --no-startup-id xsel > ~/Dropbox/clipboard/$(date -In)
bindsym $mod+semicolon exec --no-startup-id ~/projects/articles/client-qml/client-qml
bindsym $mod+Return exec --no-startup-id konsole # xterm
# bindsym $mod+backslash exec emacsclient -n -c -a emacs # -e '(eshell t)'
bindsym $mod+backslash exec --no-startup-id start-emacs

bindsym $mod+e mode "resize"
bindsym $mod+w exec --no-startup-id quickswitch

bindsym $mod+f fullscreen
bindsym $mod+q kill
bindsym $mod+apostrophe exec --no-startup-id gnome-screensaver-command -l

bindsym $mod+r exec --no-startup-id dmenu_run
bindsym $mod+g exec --no-startup-id i3-dmenu-desktop

bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

bindsym $mod+Shift+h move left 60 px
bindsym $mod+Shift+j move down 60 px
bindsym $mod+Shift+k move up 60 px
bindsym $mod+Shift+l move right 60 px

bindsym $mod+d split v
bindsym $mod+s split h
bindsym $mod+Shift+d layout stacking
bindsym $mod+Shift+s layout tabbed

# bindsym $mod+a layout toggle split
# bindsym $mod+v layout stacking
# bindsym $mod+s layout tabbed

bindsym $mod+space focus mode_toggle
bindsym $mod+Shift+space floating toggle
bindsym $mod+Shift+Return floating toggle

bindsym $mod+y focus parent
bindsym $mod+a focus child

bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

bindsym $mod+Shift+c reload
#bindsym $mod+Shift+p restart
#bindsym $mod+Shift+q exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"
bindsym  $mod+Shift+q exec --no-startup-id i3-msg exit

mode "resize" {

        bindsym Shift+h move left 30 px
        bindsym Shift+j move down 30 px
        bindsym Shift+k move up 30 px
        bindsym Shift+l move right 30 px

        bindsym h resize shrink width 20 px or 20 ppt
        bindsym j resize grow height 20 px or 20 ppt
        bindsym k resize shrink height 20 px or 20 ppt
        bindsym l resize grow width 20 px or 20 ppt

        bindsym Control+h resize shrink width 5 px or 5 ppt
        bindsym Control+j resize grow height 5 px or 5 ppt
        bindsym Control+k resize shrink height 5 px or 5 ppt
        bindsym Control+l resize grow width 5 px or 5 ppt

        bindsym $mod+h focus left
        bindsym $mod+j focus down
        bindsym $mod+k focus up
        bindsym $mod+l focus right

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym space mode "default"
}

bar {
        status_command i3status
        i3bar_command i3bar -t
        position bottom
        # mode hide
        # hidden_state hide
        # border #ffffff
        modifier $mod
        font pango:Hasklig 8
        tray_padding 0
        separator_symbol "     "
        workspace_buttons yes
        # strip_workspace_buttons yes
        height 16
        colors {
               background #1c1c1c00
               statusline #ffffff
               # statusline #cccccc
               focused_workspace #ffffff44 #ffffff00 #ffffffaa
               active_workspace #ffffff00 #ffffff00 #ffffffaa
               inactive_workspace #ffffff00 #ffffff00 #ffffffaa
               urgent_workspace #ffffff00 #ffffff00 #ff0000aa
        }
}
