#!/usr/bin/env python3

import sys
import humanfriendly

totals = []

for line in sys.stdin:
    row = line.strip().split()
    while len(totals) < len(row):
        totals.append(0)
    for i, cell in enumerate(row):
        totals[i] += humanfriendly.parse_size(cell)

print(', '.join(map(humanfriendly.format_size, totals)))
